package com.jmakulec.texttoospeech;


import org.pushingpixels.substance.api.SubstanceCortex;
import org.pushingpixels.substance.api.skin.*;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

public class AppGUI {
    // declarations
    private double totalCorruptedLetterCount = 0;
    private int totalPolishSymbolsCount = 0;
    private String fileToPlayPath;
    private JFrame frame;
    public AudioFilePlayer playingThread;
    // ------ components generated by AppGuiForm
    private JPanel rootPanel;
    private JPanel entryPanel;
    private JPanel OptionsPanel;
    private JRadioButton fileSelect;
    private JRadioButton textEntry;
    private JCheckBox analysis;
    private JPanel entryValuePanel;
    private JPanel fileInputPanel;
    private JPanel textInputPanel;
    private JTextArea inputTextArea;
    private JTextField fileInputField;
    private JButton fileChooserButton;
    private JPanel navigationPanel;
    private JButton playButton;
    private JButton stopButton;
    private JButton cleanButton;
    private JMenu optionsMenu;
    private JMenuItem libraryButton;

    public AppGUI() {

        /*try {
            UIManager.setLookAndFeel(new SubstanceDustLookAndFeel());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }*///SwingUtilities.updateComponentTreeUI(frame);

        playingThread = new AudioFilePlayer();
        // SoundLibraryContent.inputLibrary("E:\\Dokumenty\\PracaInz\\soundfiles\\"); // - library added in code
        frame = new JFrame("Syntezer mowy");
        frame.setContentPane(rootPanel); //setting the panel from GUIform in the frame
        frame.setMinimumSize(new Dimension(450, 600));
        frame.setLocationRelativeTo(null); // centering the frame
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        SubstanceCortex.GlobalScope.setSkin(new CremeCoffeeSkin());
        SwingUtilities.updateComponentTreeUI(frame);

        //setting initial option -> text input
        textEntry.setSelected(true);

        frame.pack();
        frame.setVisible(true);


        if (!SoundLibraryContent.isInitLibrary()) {
            while (SoundLibraryContent.isFileMapEmpty()) {
                setLibrary();
                if (SoundLibraryContent.getLibraryPath() == null) {
                    JOptionPane.showMessageDialog(frame,
                            "Należy wybrać ścieżkę biblioteki z dźwiękami",
                            "Błąd",
                            JOptionPane.WARNING_MESSAGE);
                }
                else if (SoundLibraryContent.isFileMapEmpty()) {
                    JOptionPane.showMessageDialog(frame,
                            "Zły folder. W folderze z biblioteką dźwięków powinny znajdować się pliki z rozszerzeniem .wav",
                            "Błąd",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        playButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (fileSelect.isSelected()) {
                    File file = new File(fileToPlayPath);
                    if (file.getName().contains(".txt") || file.getName().contains(".text")) playSound(Utils.TextProcessing.txtFileProcessor(file));
                    else if(file.getName().contains(".pdf")) playSound(Utils.TextProcessing.pdfProcessor(file));
                    else JOptionPane.showMessageDialog(frame,
                                "Zły format pliku. \nDozwolone są jedynie pliki .txt i .pdf",
                                "Błąd",
                                JOptionPane.ERROR_MESSAGE);
                }
                else if (inputTextArea.getText().length() != 0) {
                    playSound(Utils.TextProcessing.sliceText(inputTextArea.getText()));
                }
            }
        });
        cleanButton.addActionListener(e -> {
            inputTextArea.setText("");
            fileToPlayPath = "";
            fileInputField.setText("");
        });
        stopButton.addActionListener(e -> {
           if (playingThread.isAlive()) playingThread.cancelPlaying();
        });
        libraryButton.addActionListener(e -> {
            setLibrary();
        });
        fileChooserButton.addActionListener(e -> {
            fileSelect.setSelected(true);
            JFileChooser fileChooser = new JFileChooser(); // creating a file chooser
            fileChooser.setDialogTitle("Wybierz plik do odtworzenia");
            FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("Pliki tekstowe i PDF", "txt", "text", "pdf"); // creating filter allowing only pdf and txt
            fileChooser.setFileFilter(extensionFilter);

            int state = fileChooser.showOpenDialog(frame);

            if (state == JFileChooser.APPROVE_OPTION) {
                fileToPlayPath = fileChooser.getSelectedFile().getAbsolutePath();
                fileInputField.setText(fileChooser.getSelectedFile().getAbsolutePath());
            }
        });
        textEntry.addActionListener(e -> {
            fileInputField.setEditable(false);
            inputTextArea.setEditable(true);
        });
        fileSelect.addActionListener(e -> {
            fileInputField.setEditable(true);
            inputTextArea.setEditable(false);
        });
        inputTextArea.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println("yup");
                textEntry.setSelected(true);
                fileInputField.setEditable(false);
                inputTextArea.setEditable(true);
            }
        });
    }

    public static void main(String[] args) {
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                new AppGUI();
            }
        };
        SwingUtilities.invokeLater(runnable);

    }
    
    private void playSound(ArrayList<String> input) {
        totalCorruptedLetterCount = 0;
        totalPolishSymbolsCount = 0;
        ArrayList<AudioInputStream> wordFileList = new ArrayList<>();
        for (String s: input){
            try {
                wordFileList.add(AudioAppender.appendFiles(WordSlicer.sliceText(s, analysis.isSelected())));
                if (analysis.isSelected()) {
                    totalCorruptedLetterCount += WordSlicer.corruptedCount;
                    totalPolishSymbolsCount += WordSlicer.polishSymbolsCount;
                }
                //AudioFilePlayer.playFile(AudioAppender.appendFiles(WordSlicer.sliceText(s)));
            } catch (IOException | UnsupportedAudioFileException exception) {
                exception.printStackTrace();
            }
        }
        try {
            AudioFilePlayer.setPlayableInput( AudioAppender.appendWords(wordFileList) );
            if (playingThread.isAlive()) playingThread.cancelPlaying();
            playingThread = new AudioFilePlayer();
            playingThread.start();
        } catch (IOException | UnsupportedAudioFileException exception) {
            exception.printStackTrace();
        }
        if (analysis.isSelected()) {
            double totalLetterCount = input.stream().mapToInt(String::length).sum();
            Double coveragePercent = totalCorruptedLetterCount !=0 ? 100.00 - totalCorruptedLetterCount/(totalLetterCount - totalPolishSymbolsCount) * 100 : 0;
            coveragePercent = Utils.OtherUtils.round(coveragePercent, 2);
            JOptionPane.showMessageDialog(frame,
                    "Biblioteka dźwięków pokrywa około " + coveragePercent + "% odtwarzanego tekstu");
        }
    }

    private void setLibrary() {
        JFileChooser libraryChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        libraryChooser.setDialogTitle("Wybierz ścieżkę biblioteki dźwięków");
        libraryChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = libraryChooser.showDialog(frame, "Wybierz");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            SoundLibraryContent.inputLibrary(libraryChooser.getSelectedFile().getAbsolutePath() + "\\");
            SoundLibraryContent.saveLibraryPath(libraryChooser.getSelectedFile().getAbsolutePath() + "\\");
        }
    }
}
